@@assert.exec "@@assert.fail" false
@@assert.exec "@@assert.fail" false '"asd"'

@@assert.exec "@@assert.true" true true
@@assert.exec "@@assert.true" false false
@@assert.exec "@@assert.true" false '"x"'

@@assert.exec "@@assert.false" true false
@@assert.exec "@@assert.false" false true
@@assert.exec "@@assert.false" false '"x"'

@@assert.exec "@@assert.empty" true '""'
@@assert.exec "@@assert.empty" false '"x"'
@@assert.exec "@@assert.empty" false '"${BX_KEY_ESC}"'
@@assert.exec "@@assert.empty" false '" "'
@@assert.exec "@@assert.empty" false '"\t"'
@@assert.exec "@@assert.empty" false '"\n"'

@@assert.exec "@@assert.notEmpty" true 'x'
@@assert.exec "@@assert.notEmpty" true '" "'
@@assert.exec "@@assert.notEmpty" true '"\t"'
@@assert.exec "@@assert.notEmpty" true '"\n"'
@@assert.exec "@@assert.notEmpty" true '"${BX_KEY_ESC}"'
@@assert.exec "@@assert.notEmpty" false '""'

@@assert.exec "@@assert.number" true '1'
@@assert.exec "@@assert.number" true '0'
@@assert.exec "@@assert.number" true '00'
@@assert.exec "@@assert.number" true '10'
@@assert.exec "@@assert.number" true '5'
@@assert.exec "@@assert.number" false '-1'
@@assert.exec "@@assert.number" false '""'
@@assert.exec "@@assert.number" false '" "'
@@assert.exec "@@assert.number" false '" 1"'
@@assert.exec "@@assert.number" false '"1 "'
@@assert.exec "@@assert.number" false '"1 1"'
@@assert.exec "@@assert.number" false 'x'

@@assert.exec "@@assert.errorCode" true '1'
@@assert.exec "@@assert.errorCode" true '10'
@@assert.exec "@@assert.errorCode" true '255'
@@assert.exec "@@assert.errorCode" false '256'
@@assert.exec "@@assert.errorCode" false '300'
@@assert.exec "@@assert.errorCode" false '0'
@@assert.exec "@@assert.errorCode" false '""'
@@assert.exec "@@assert.errorCode" false '" "'
@@assert.exec "@@assert.errorCode" false 'x'
@@assert.exec "@@assert.errorCode" false '"1 "'
@@assert.exec "@@assert.errorCode" false '" 1"'
@@assert.exec "@@assert.errorCode" false '"1 1"'

@@assert.exec "@@assert.notErrorCode" true '0'
@@assert.exec "@@assert.notErrorCode" false '1'
@@assert.exec "@@assert.notErrorCode" false '10'
@@assert.exec "@@assert.notErrorCode" false '255'
@@assert.exec "@@assert.notErrorCode" false '300'
@@assert.exec "@@assert.notErrorCode" false '""'
@@assert.exec "@@assert.notErrorCode" false '" "'
@@assert.exec "@@assert.notErrorCode" false 'x'
@@assert.exec "@@assert.notErrorCode" false '"1 "'
@@assert.exec "@@assert.notErrorCode" false '" 1"'
@@assert.exec "@@assert.notErrorCode" false '"1 1"'

@@assert.exec "@@assert.equal" true '1 1'
@@assert.exec "@@assert.equal" true 'a a'
@@assert.exec "@@assert.equal" true '0 0'
@@assert.exec "@@assert.equal" true '"" ""'
@@assert.exec "@@assert.equal" true '"${BX_KEY_ESC}" "${BX_KEY_ESC}"'
@@assert.exec "@@assert.equal" false 'a A'
@@assert.exec "@@assert.equal" false 'A a'
@@assert.exec "@@assert.equal" false '"" 0'

@@assert.exec "@@assert.notEqual" true 'a A'
@@assert.exec "@@assert.notEqual" true 'A a'
@@assert.exec "@@assert.notEqual" true '"" 0'
@@assert.exec "@@assert.notEqual" false '1 1'
@@assert.exec "@@assert.notEqual" false 'a a'
@@assert.exec "@@assert.notEqual" false '0 0'
@@assert.exec "@@assert.notEqual" false '"" ""'
@@assert.exec "@@assert.notEqual" false '"${BX_KEY_ESC}" "${BX_KEY_ESC}"'

@@assert.exec "@@assert.contains" true 'abc b'
@@assert.exec "@@assert.contains" true 'abc a'
@@assert.exec "@@assert.contains" true 'abc c'
@@assert.exec "@@assert.contains" true 'abc bc'
@@assert.exec "@@assert.contains" true 'abc abc'
@@assert.exec "@@assert.contains" false '"" ""'
@@assert.exec "@@assert.contains" false 'abc x'
@@assert.exec "@@assert.contains" false 'abc A'
@@assert.exec "@@assert.contains" false 'abc ""'
@@assert.exec "@@assert.contains" false 'abc B'

@@assert.exec "@@assert.notContains" true 'abc x'
@@assert.exec "@@assert.notContains" true 'abc A'
@@assert.exec "@@assert.notContains" true 'abc B'
@@assert.exec "@@assert.notContains" false 'abc ""'
@@assert.exec "@@assert.notContains" false '"" ""'
@@assert.exec "@@assert.notContains" false 'abc b'
@@assert.exec "@@assert.notContains" false 'abc a'
@@assert.exec "@@assert.notContains" false 'abc c'
@@assert.exec "@@assert.notContains" false 'abc bc'
@@assert.exec "@@assert.notContains" false 'abc abc'

@@assert.exec "@@assert.stdOut" true '"echo asd"'
@@assert.exec "@@assert.stdOut" true '"echo \"${BX_KEY_ESC}\""'
@@assert.exec "@@assert.stdOut" false '"echo asd >&2"'
@@assert.exec "@@assert.stdOut" false '"echo"'

@@assert.exec "@@assert.noStdOut" true '"echo asd >&2"'
@@assert.exec "@@assert.noStdOut" true '"echo"'
@@assert.exec "@@assert.noStdOut" false '"echo asd"'
@@assert.exec "@@assert.noStdOut" false '"echo \"${BX_KEY_ESC}\""'

@@assert.exec "@@assert.errOut" true '"echo asd >&2"'
@@assert.exec "@@assert.errOut" true '"echo \"${BX_KEY_ESC}\" >&2"'
@@assert.exec "@@assert.errOut" false '"echo"'
@@assert.exec "@@assert.errOut" false '"echo asd"'

@@assert.exec "@@assert.noErrOut" true '"echo"'
@@assert.exec "@@assert.noErrOut" true '"echo asd"'
@@assert.exec "@@assert.noErrOut" false '"echo asd >&2"'
@@assert.exec "@@assert.noErrOut" false '"echo \"${BX_KEY_ESC}\" >&2"'

@@assert.exec "@@assert.noOut" true '"echo"'
@@assert.exec "@@assert.noOut" false '"echo asd"'
@@assert.exec "@@assert.noOut" false '"echo asd >&2"'
@@assert.exec "@@assert.noOut" false '"echo asd >&3"'
@@assert.exec "@@assert.noOut" false '"echo \"${BX_KEY_ESC}\""'
@@assert.exec "@@assert.noOut" false '"echo \"${BX_KEY_ESC}\" >&2"'
@@assert.exec "@@assert.noOut" false '"echo \"${BX_KEY_ESC}\" >&3"'
