@@assert.noOut '@is-number'
@@assert.noOut '@is-number 0'
@@assert.noOut '@is-number asd'
@@assert.noOut '@is-number ""'
@@assert.noOut '@is-number " "'

@@assert.exec '@is-number' true '0'
@@assert.exec '@is-number' true '1'
@@assert.exec '@is-number' true '01'
@@assert.exec '@is-number' true '10'
@@assert.exec '@is-number' true '99'


@@assert.exec '@is-number' false ''
@@assert.exec '@is-number' false 'a'
@@assert.exec '@is-number' false '" 0"'
@@assert.exec '@is-number' false '"0 "'
@@assert.exec '@is-number' false '" 0 "'
@@assert.exec '@is-number' false '"1 0"'
@@assert.exec '@is-number' false '""'
