#!/bin/bash

# ################### #
#                     #
# Application Manager #
#                     #
# ################### #

# BashX Required Version (INTEGER) | bashx.version
BASHX_REQUIRED_VERSION=200

BASE_SOURCE="$0"
BASE_DIR="$(cd "$(dirname "$BASE_SOURCE")" ; pwd)"
while [ -h "$BASE_SOURCE" ]; do
  BASE_SOURCE="$(readlink "$BASE_SOURCE")"
  BASE_DIR="$(cd "$BASE_DIR" ; cd "$(dirname "$BASE_SOURCE")" ; pwd)"
  BASE_SOURCE="$(cd "$BASE_DIR" ; pwd)/$(basename "$BASE_SOURCE")"
done
export BASE_SOURCE="$BASE_SOURCE"
export BASE_DIR="$BASE_DIR"
export CURRENT_DIR="$(pwd)"
export CURRENT_SOURCE="$CURRENT_DIR/$(basename "$0")"
export CONFIG_FILE="$BASE_DIR/src/config.ini"
#export BASHX_DIR="$BASE_DIR/src/bashx"
export BASHX_DIR="$BASE_DIR"
cd "$BASE_DIR"

if [ ! -d "${BASHX_DIR}" ]; then
  echo "# Installing BashX..."
  if ! type git &>/dev/null
    then
      if ! sudo apt-get install git
        then
          echo "# Error installing GIT"
          exit 1
        fi
    fi
  if ! git clone https://github.com/reduardo7/bashx.git "${BASHX_DIR}"
    then
      echo "# Error installing BashX"
      exit 1
    fi
else
  BASHX_CURRENT_VERSION=`cat "${BASHX_DIR}/src/bashx.version" 2>/dev/null || echo 0`
  if [[ $BASHX_CURRENT_VERSION -lt $BASHX_REQUIRED_VERSION ]]; then
    (
      echo "# BashX requred version is $BASHX_REQUIRED_VERSION, but version $BASHX_CURRENT_VERSION is installed"
      echo "# Updating BashX..."
      cd "${BASHX_DIR}"
      if ! git pull
        then
          echo "# Error updating BashX"
          exit 1
        fi
    )
  fi
fi

. "${BASHX_DIR}/src/bashx.sh"
run "$@"
