#!/usr/bin/env bash

# BashX | https://github.com/reduardo7/bashx
export BASHX_VERSION="master"
bash -c "$(echo 'ZXhwb3J0IExDX0NUWVBFPUMKZXhwb3J0IExDX0FMTD1DCmV4cG9ydCBCQVNIWF9ESVI9IiR7SE9N
RX0vLmJhc2h4LyR7QkFTSFhfVkVSU0lPTn0iCmV4cG9ydCB0bXBfZGlyPSIkKG1rdGVtcCAtZCki
Cl9lKCkgewogIGVjaG8gIiMgJCoiCn0KX3coKSB7CiAgX2UgIiQqIiA+JjIKfQpfZXJyKCkgewog
IF93ICJFcnJvciEgJCoiCiAgZXhpdCAxCn0KWyAteiAiJHtCQVNIWF9WRVJTSU9OfSIgXSAmJiBf
ZXJyICdCQVNIWF9WRVJTSU9OIGlzIHJlcXVpcmVkJwooCnNldCAtZQppZiBbICEgLWQgIiR7QkFT
SFhfRElSfSIgXTsgdGhlbgogIF9lICJJbnN0YWxsaW5nIEJhc2hYICR7QkFTSFhfVkVSU0lPTn0u
Li4iCiAgbV9lZD0iRXJyb3IgZG93bmxvYWRpbmcgQmFzaFggJHtCQVNIWF9WRVJTSU9OfSIKICBn
X3JlcG89Imh0dHBzOi8vZ2l0aHViLmNvbS9yZWR1YXJkbzcvYmFzaHgvdGFyYmFsbC8ke0JBU0hY
X1ZFUlNJT059IgogIGNkICIke3RtcF9kaXJ9IgogIGlmIHR5cGUgd2dldCA+L2Rldi9udWxsIDI+
JjEgOyB0aGVuCiAgICB3Z2V0IC0tbm8tY2hlY2stY2VydGlmaWNhdGUgJHtnX3JlcG99IC1PIC0g
fCB0YXIgLXh6IHx8IF9lcnIgIiR7bV9lZH0iCiAgZWxpZiB0eXBlIGN1cmwgPi9kZXYvbnVsbCAy
PiYxIDsgdGhlbgogICAgY3VybCAtc0wgJHtnX3JlcG99IHwgdGFyIC14eiB8fCBfZXJyICIke21f
ZWR9IgogIGVsc2UKICAgIF9lcnIgIndnZXQgb3IgY3VybCBhcmUgcmVxdWlyZWQhIEluc3RhbGwg
d2dldCBvciBjdXJsIHRvIGNvbnRpbnVlIgogIGZpCiAgbWtkaXIgLXAgIiR7QkFTSFhfRElSfSIK
ICBybSAtcmYgIiR7QkFTSFhfRElSfSIKICBtdiByZWR1YXJkbzctYmFzaHgtKiAiJHtCQVNIWF9E
SVJ9IgpmaQopCmU9JD8Kcm0gLXJmICIke3RtcF9kaXJ9IiA+L2Rldi9udWxsIDI+JjEKZXhpdCAk
ZQo=' | base64 -d)" || exit $?
. "${HOME}/.bashx/${BASHX_VERSION}/init"

### Begin Example ###

@Actions.action1() { # \\n Action without arguments
  # ... Your code here ...
  @print Action 1
}

@Actions.action2() { # param1 param2 \\n Action with arguments
  # ... Your code here ...
  @print Action 2
  @print Param1: $1
  @print Param2: $2
}

### End Example ###

@run-app "$@"
