#!/usr/bin/env bash

############################################
#                                          #
# BashX                                    #
#                                          #
# Extended Bash Framework                  #
#                                          #
# URL: https://github.com/reduardo7/bashx  #
#                                          #
# Author: Eduardo Daniel Cuomo             #
#         eduardo.cuomo.ar@gmail.com       #
#         reduardo7@gmail.com              #
#                                          #
############################################

set +e

[ -z "${LC_CTYPE}" ] && export LC_CTYPE=C || true
[ -z "${LC_ALL}" ] && export LC_ALL="${LC_CTYPE}" || true

BX_SCRIPT_CALLED="$0"
BX_SCRIPT_DIR="$(cd "$(dirname "${BX_SCRIPT_CALLED}")" ; pwd)"
BX_SCRIPT_FILE_NAME="$(basename "${BX_SCRIPT_CALLED}")"
while [ -h "${BX_SCRIPT_CALLED}" ]; do
  BX_SCRIPT_CALLED="$(readlink "${BX_SCRIPT_CALLED}")"
  BX_SCRIPT_DIR="$(cd "${{BX_SCRIPT_DIR}}" ; cd "$(dirname "${BX_SCRIPT_CALLED}")" ; pwd)"
  BX_SCRIPT_FILE_NAME="$(basename "${BX_SCRIPT_CALLED}")"
  BX_SCRIPT_CALLED="$(cd "${BX_SCRIPT_DIR}" ; pwd)/${BX_SCRIPT_FILE_NAME}"
done

# Test and force run with "bash" interpreter
if [ -z "$BASH" ]; then
  bash "$(basename "${BX_SCRIPT_CALLED}")" "$@"
  exit $?
fi

# #############################################################################

### Constants

export BX_CURRENT_DIR="$(pwd)"
## Current user directory.
readonly BX_CURRENT_DIR="${BX_CURRENT_DIR}"

export BX_SCRIPT_CALLED="${BX_SCRIPT_CALLED}"
## Called script.
readonly BX_SCRIPT_CALLED="${BX_SCRIPT_CALLED}"

export BX_SCRIPT_FILE_NAME="${BX_SCRIPT_FILE_NAME}"
## Current script file name.
readonly BX_SCRIPT_FILE_NAME="${BX_SCRIPT_FILE_NAME}"

export BX_SCRIPT_FULL_PATH="${BX_SCRIPT_DIR}/${BX_SCRIPT_FILE_NAME}"
## Current script full path.
readonly BX_SCRIPT_FULL_PATH="${BX_SCRIPT_FULL_PATH}"

export BX_SCRIPT_DIR="${BX_SCRIPT_DIR}"
## Current script directory.
readonly BX_SCRIPT_DIR="${BX_SCRIPT_DIR}"

export BASHX_DIR="${BASHX_DIR:-${HOME:-/tmp}/.bashx/${BASHX_VERSION}}"
## Core directory (can be overridden before load).
readonly BASHX_DIR="${BASHX_DIR}"

export BASHX_SRC_PATH="${BASHX_DIR}/src"
## Core SRC path.
readonly BASHX_SRC_PATH="${BASHX_SRC_PATH}"

export BASHX_ACTIONS_PATH="${BASHX_SRC_PATH}/actions"
## Core actions path.
readonly BASHX_ACTIONS_PATH="${BASHX_ACTIONS_PATH}"

export BASHX_UTILS_PATH="${BASHX_SRC_PATH}/utils"
## Core utils path.
readonly BASHX_UTILS_PATH="${BASHX_UTILS_PATH}"


### OS

export BASHX_OS_IS_LINUX=false
export BASHX_OS_IS_MAC=false
export BASHX_OS_IS_MINGW=false

if [ "$(uname)" == "Darwin" ]; then
  defaults write org.R-project.R force.LANG en_US.UTF-8
  export TERM="xterm-color"
  export BASHX_OS_IS_MAC=true
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  export BASHX_OS_IS_LINUX=true
elif [[ "$(expr substr $(uname -s) 1 10)" == MINGW* ]]; then
  export BASHX_OS_IS_MINGW=true
fi

## Is Linux OS?
readonly BASHX_OS_IS_LINUX=${BASHX_OS_IS_LINUX}
## Is Mac OS?
readonly BASHX_OS_IS_MAC=${BASHX_OS_IS_MAC}
## Is Win OS?
readonly BASHX_OS_IS_MINGW=${BASHX_OS_IS_MINGW}

BASHX_BASE_SOURCE="${BASH_SOURCE[0]}"
while [ -h "${BASHX_BASE_SOURCE}" ]; do
  BASHX_BASE_DIR="$(cd -P "$(dirname "${BASHX_BASE_SOURCE}")" && pwd)"
  BASHX_BASE_SOURCE=`readlink "${BASHX_BASE_SOURCE}"`
  [[ "${BASHX_BASE_SOURCE}" != /* ]] && BASHX_BASE_SOURCE="${BASHX_BASE_DIR}/${BASHX_BASE_SOURCE}"
done
[ -z "${BASHX_BASE_DIR}"] && BASHX_BASE_DIR="$(cd -P "$(dirname "${BASHX_BASE_SOURCE}")" && pwd)"
export BASHX_BASE_SOURCE="${BASHX_BASE_SOURCE}"
## BashX base source path.
readonly BASHX_BASE_SOURCE="${BASHX_BASE_SOURCE}"

export BASHX_BASE_DIR="${BASHX_BASE_DIR}"
# BashX base directory path.
readonly BASHX_BASE_DIR="${BASHX_BASE_DIR}"

# \e | \033 | \x1B
$BASHX_OS_IS_MAC && export BASHX_KEY_ESC=$'\x1B' || export BASHX_KEY_ESC=$'\e'
## Key: ESC
readonly BASHX_KEY_ESC="${BASHX_KEY_ESC}"

# \n - New Line
export BASHX_NL='
'
## New Line constant (\n)
readonly BASHX_NL="${BASHX_NL}"

# \t - Tab
export BASHX_TAB='  '
## New Line constant (\t)
readonly BASHX_TAB="${BASHX_TAB}"

export BASHX_ACTION_PREFIX='@Actions'
## Action prefix. Used at @run-app.
readonly BASHX_ACTION_PREFIX="${BASHX_ACTION_PREFIX}"

# #############################################################################

### Configs

export BASHX_DOC_MARK='##'

## Current script Sources directory. Customizable with: BX_SRC_DIR.
export BX_SRC_DIR="${BX_SRC_DIR:-${BX_SCRIPT_FILE_NAME}.src}"

## Current script Sources path. Constant.
export BX_SRC_PATH="${BX_SCRIPT_DIR}/${BX_SRC_DIR}"

## Configuration file (can be overridden before load). Customizable with: BASHX_APP_CONFIG_FILE.
export BX_APP_CONFIG_FILE="${BASHX_APP_CONFIG_FILE:-${BX_SCRIPT_DIR}/.${BX_SCRIPT_FILE_NAME}.env}"

## APP Title. Customizable with: BASHX_APP_CONFIG_FILE.
export BX_APP_TITLE="BashX"

## APP Version.
export BX_APP_VERSION="1.0"

## Default APP color. See "@style" for more information.
export BX_APP_COLOR_DEFAULT="cyan-light"

## Output colors?
export BX_APP_COLORS_ENABLED=true

## APP colsumns width.
export BX_APP_WIDTH=80

## Start character for formated print screen. See "@print" for more information.
export BX_APP_PRINT_PREFIX="#"

## Default action to call. Action to use if script called without arguments.
export BX_APP_DEFAULT_ACTION="help"

## Log file path.
export BX_LOG_FILE_PATH="${BX_SCRIPT_FULL_PATH}.log"

## Tests path.
export BX_TESTS_PATH="${BX_SRC_PATH}/tests"

## Actions path.
export BX_ACTIONS_PATH="${BX_SRC_PATH}/actions"

## Utils path.
export BX_UTILS_PATH="${BX_SRC_PATH}/utils"

## Events path.
export BX_EVENTS_PATH="${BX_SRC_PATH}/events"

## Resources path.
export BX_RESOURCES_PATH="${BX_SRC_PATH}/resources"

## Valid events options.
export BASHX_EVENTS_OPTS=(invalid-action ready start error finish)
readonly BASHX_EVENTS_OPTS=${BASHX_EVENTS_OPTS}

# #############################################################################

### Load config

if [ -f "${BX_APP_CONFIG_FILE}" ]; then
  . "${BX_APP_CONFIG_FILE}"
fi

# #############################################################################

### VARS

## Current called action.
export BASHX_ACTION=''

## APP Temporary path.
export BX_APP_TMP_PATH="$(mktemp -d)"

## True if APP is terminated with illegal error
BASHX_APP_EXIT_ILLEGAL_ERROR=false

# #############################################################################

### PRIVATE VARS

# On exit command
_BASHX_ON_EXIT=''

# True if APP is terminated
_BASHX_APP_EXIT=false

# #############################################################################

# info out > std out
exec 3>&1

# #############################################################################

### Preload required

@trim() { . "${BASHX_UTILS_PATH}/trim.sh"; }
@str-to-lower() { . "${BASHX_UTILS_PATH}/str-to-lower.sh"; }
@style() { . "${BASHX_UTILS_PATH}/style.sh"; }
@file-name() { . "${BASHX_UTILS_PATH}/file-name.sh"; }
@load-functions() { . "${BASHX_UTILS_PATH}/load-functions.sh"; }

# #############################################################################

### Bootstrap

# Load base
@load-functions "${BASHX_UTILS_PATH}" '@'
@load-functions "${BASHX_ACTIONS_PATH}" "${BASHX_ACTION_PREFIX}."

# Load custom
[ ! -d "${BX_UTILS_PATH}" ] || @load-functions "${BX_UTILS_PATH}"
[ ! -d "${BX_ACTIONS_PATH}" ] || @load-functions "${BX_ACTIONS_PATH}" "${BASHX_ACTION_PREFIX}."
