fwUtils.commonAction "$1" "$2" "${BX_ACTIONS_PATH}" <<EOF
${BASHX_DOC_MARK} param1 [param2]
${BASHX_DOC_MARK} Description...
${BASHX_DOC_MARK}
${BASHX_DOC_MARK} Params:
${BASHX_DOC_MARK}   param1: {String} Description...
${BASHX_DOC_MARK}   param2: {Type} Description...
${BASHX_DOC_MARK}           Optional. Default: ...

@throw-not-implemented '@TODO'
EOF
