fwUtils.commonAction "$1" "$2" "${BASHX_UTILS_PATH}" <<EOF
${BASHX_DOC_MARK} param1 [param2]
${BASHX_DOC_MARK} Description...
${BASHX_DOC_MARK}
${BASHX_DOC_MARK} Params:
${BASHX_DOC_MARK}   param1: {String} Description...
${BASHX_DOC_MARK}   param2: {Type} Description...
${BASHX_DOC_MARK}           Optional. Default: ...

@throw.notImplemented '@TODO'
EOF

# vim: filetype=sh tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
