name: Test Scripts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        # @TODO: Following test is not working
        # at GitHub context: `./bashx _run-tests`
        # run: ./bashx _run-tests-all
        run: ./bashx _run-tests-docker
